-- The canonical DDL for this service's tables lives in the MES migration:
--   services/operations/mes/migrations/006_machine_telemetry.sql
--
-- This service speaks the shared `asset_tag` machine identity and writes against
-- the MES-owned `mes` schema. It creates NO tables of its own. Summary:
--
--   mes_assets                  — canonical machine/asset master  (MES, existing)
--   mes_asset_telemetry_latest  — live per-metric values          (MES, existing)
--   mes_downtime_events         — CMMS downtime (auto + manual)    (MES, existing)
--   mes_machine_telemetry       — readings hypertable (Timescale)  (added by 006)
--   mes_machine_oee_daily       — daily OEE rollup                 (added by 006)
--   mes_iot_devices             — device registry                 (added by 006)
--
-- Requires the TimescaleDB extension for the mes_machine_telemetry hypertable.
-- See that migration for the authoritative column definitions.
